name: Test MuSig2 Library

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test-library:
        runs-on: ubuntu-latest
        env:
            TOOLCHAIN: stable
        steps:
            -   name: Checkout source code
                uses: actions/checkout@v3
            -   name: Install Rust ${{ matrix.toolchain }} toolchain
                uses: actions-rs/toolchain@v1
                with:
                    toolchain: stable
                    override: true
                    profile: minimal
            -   name: Build
                run: cargo build --verbose --color always
            -   name: Test
                run: cargo test --verbose --color always
            -   name: Document
                run: cargo doc --document-private-items --verbose --color always
            -   name: Check
                run: cargo check --verbose --color always
